const { contextBridge, ipcRenderer } = require("electron");
const allowed = new Set([
  "state",
  "project:add",
  "project:open-editor",
  "project:tree",
  "editor:state",
  "editor:confirm-discard",
  "agent:create",
  "agent:update",
  "agent:queue",
  "task:start",
  "task:resolve",
  "agent:start",
  "agent:mark",
  "agent:handoff",
  "ui:update",
  "files:list",
  "files:read",
  "files:save",
  "files:reload",
  "draft:save",
  "skills:list",
  "terminal:start",
  "terminal:recover",
  "terminal:bind",
  "terminal:write",
  "terminal:resize",
  "terminal:stop",
  "terminal:log",
  "terminal:dismiss",
  "git:status",
  "git:log",
  "git:diff",
  "git:commit",
  "git:push",
  "git:discard",
  "git:repos",
  "git:agent-changes",
  "git:file-changes",
  "git:hunks",
  "git:revert-hunk",
  "git:menu",
  "git:run",
  "git:fetch",
  "git:pull",
  "git:sync",
  "git:branches",
  "git:checkout",
  "git:stash",
  "search:files",
  "search:replace",
  "containers:list",
  "containers:logs",
  "containers:stop",
  "chat:create",
  "chat:send",
  "chat:cancel",
  "chat:configure",
  "chat:revert",
  "approval:resolve",
  "recovery:report",
  "sessions:summaries",
  "lang:completions",
  "lang:diagnostics",
  "lang:hover",
  "lang:detail",
  "chat:modes",
  "settings:execution",
  "settings:save",
  "usage:export",
]);
contextBridge.exposeInMainWorld("relay", {
  call(name, args = {}) {
    if (!allowed.has(name)) return Promise.reject(new Error("Unknown command"));
    return ipcRenderer.invoke(`relay:${name}`, args);
  },
  subscribe(callback) {
    const listener = (_event, value) => callback(value);
    ipcRenderer.on("relay:event", listener);
    return () => ipcRenderer.removeListener("relay:event", listener);
  },
});
